### ISSUE TITLE
管理页面地址问题

### ISSUE THREAD

**Issue by foxlovecat** [lejianwen/rustdesk-server#10]
docker-compose.yml文件内容如下
```
networks:
  rustdesk-net:
    external: false
services:
  rustdesk-server:
    container_name: rustdesk-server
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    image: ghcr.io/rustdesk/rustdesk-server-s6:latest
    environment:
      - RELAY=121.129.68.17:21117
      - ENCRYPTED_ONLY=1
      - KEY=4hVQBa***4kUQEE4  #自定义KEY
    volumes:
      - /data/rustdesk-s6/server:/data
      - /data/rustdesk-s6/server/hbbr/run:/etc/s6-overlay/s6-rc.d/hbbr/run
      - /data/rustdesk-s6/server/hbbs/run:/etc/s6-overlay/s6-rc.d/hbbs/run
    restart: unless-stopped
  rustdesk-api:
    container_name: rustdesk-api
    ports:
      - 21114:21114
    image: ghcr.io/lejianwen/rustdesk-api
    environment:
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=121.129.68.17:21116 #21116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=121.129.68.17:21117 #21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://121.129.68.17:21114 #21114
      - RUSTDESK_API_RUSTDESK_KEY=4hV***E4
    volumes:
      - /data/rustdesk-s6/api:/app/data
    networks:
      - rustdesk-net
    restart: unless-stopped
```
 
启动后客户端可以连接上,但是后台管理页面打不开测试了如下地址都不行
http://121.129.68.17:21114
http://121.129.68.17:21114/_admin/
http://121.129.68.17:21114/admin/
