### ISSUE TITLE
是否可以用环境变量指定web client的连接地址

### ISSUE THREAD

**Issue by StarCode000** [lejianwen/rustdesk-server#4]
大佬，我用了nginx反向代理了rustdesk-api提供的21114端口并且配置了ssl证书，然后通过rustdesk-api的管理员页面连接时，发现未经反向代理的21114端口上的管理员页面能用web client正常连接其他电脑，但是经过反向代理并且配置了ssl证书的端口（我这里是50034端口）上的管理员页面，在使用web client的时候，会使用wss协议去访问21118端口（21118端口并未配置ssl证书），导致无法连接。所以能不能在环境变量中指定一下web client的连接地址？如果能指定webclient连接地址，那么我就可以对21118和21119端口做一下反向代理并且配置ssl证书
## 使用了反向代理+https的情况
![Image](https://github.com/user-attachments/assets/7fb0148c-3b64-495d-b05e-a1efd4a1e6c8)

## 未使用反向代理和https的情况
![Image](https://github.com/user-attachments/assets/94d386c7-1a2f-4592-bdcb-4f16e39e82bc)

## 附我的docker-compose文件
```yaml
networks:
  rustdesk-net:
    external: false
services:
  rustdesk:
    container_name: rustdesk-server-with-api
    ports:
      - 21114:21114
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    image: lejianwen/rustdesk-server-s6:latest
    environment:
      - RELAY=[my hostname]:21117
      - LIMIT_SPEED=1000
      - TOTAL_BANDWIDTH=1000
      - SINGLE_BANDWIDTH=1000
      - ENCRYPTED_ONLY=1
      - MUST_LOGIN=N
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=[my hostname]:21116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=[my hostname]:21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=https://[my hostname]:50034
      - RUSTDESK_API_KEY_FILE=/data/rustdesk/server/id_ed25519.pub
      # - RUSTDESK_API_JWT_KEY=xxxxxx # jwt key
    volumes:
      - /data/rustdesk/server:/data
      - /data/rustdesk/api:/app/data #将数据库挂载
    networks:
      - rustdesk-net
    restart: unless-stopped
```
## NGINX反向代理配置
```
# rustdesk-api
server {
    server_name 【my hostname】;
    # listen 50034;
    listen 50034 ssl;
    ssl_dhparam /etc/letsencrypt/dhparam.pem;
    location / {
        proxy_read_timeout 60s;
    	proxy_set_header Host $host;
    	proxy_set_header X-Real-IP $remote_addr;
    	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    	proxy_http_version 1.1;
    	proxy_set_header Upgrade $http_upgrade;
    	proxy_set_header Connection $connection_upgrade;
        proxy_pass http://127.0.0.1:21114;
    }
}
```
