### ISSUE TITLE
连接错误-deadlinehaselapsed

### ISSUE THREAD

**Issue by superBiuBiuMan** [lejianwen/rustdesk-server#7]
![Image](https://github.com/user-attachments/assets/1d9b78f1-490b-4f67-8c77-06b89a3ddf80)

![Image](https://github.com/user-attachments/assets/a5646ce6-1fe7-4985-bb77-cc71a02aacce)

```
 networks:
   rustdesk-net:
     external: false
 services:
   rustdesk:
     ports:
       - 21114:21114
       - 21115:21115
       - 21116:21116
       - 21116:21116/udp
       - 21117:21117
       - 21118:21118
       - 21119:21119
     image: lejianwen/rustdesk-server-s6:latest
     environment:
       - RUSTDESK_API_RUSTDESK_ID_SERVER=rustdesk.abc.com:21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=rustdesk.abc.com:21117
       - RUSTDESK_API_RUSTDESK_API_SERVER=http://rustdesk-server.abc.com:21114
       - ENCRYPTED_ONLY=1
       - MUST_LOGIN=N
       - TZ=Asia/Shanghai
       - RUSTDESK_API_KEY_FILE=./data/id_ed25519.pub
       - RUSTDESK_API_JWT_KEY=ujqgLD8BOkcCUtly # jwt key
     volumes:
       - ./data/rustdesk/server:/data
       - ./data/rustdesk/api:/app/data #将数据库挂载
     networks:
       - rustdesk-net
     restart: unless-stopped
       
```

远控端和被远控端均没有登录

**Comment by superBiuBiuMan** [comment]
防火墙关闭了

**Comment by lejianwen** [comment]
运行日志是什么样的呢？

**Comment by lejianwen** [comment]
` RUSTDESK_API_KEY_FILE=./data/id_ed25519.pub`这个环境变量应该是设置错了
改成`RUSTDESK_API_KEY_FILE=/data/id_ed25519.pub`试试

**Comment by superBiuBiuMan** [comment]
* 更改为如下,然后控制端不管有没有填写API服务器都是提示deadline has elapsed

```
 networks:
   rustdesk-net:
     external: false
 services:
   rustdesk:
     ports:
       - 21114:21114
       - 21115:21115
       - 21116:21116
       - 21116:21116/udp
       - 21117:21117
       - 21118:21118
       - 21119:21119
     image: lejianwen/rustdesk-server-s6:latest
     environment:
       - RUSTDESK_API_RUSTDESK_ID_SERVER=rustdesk.abc.top:21116
       - RUSTDESK_API_RUSTDESK_RELAY_SERVER=rustdesk.abc.top:21117
       - RUSTDESK_API_RUSTDESK_API_SERVER=http://rustdesk-server.abc.top:21114
       - ENCRYPTED_ONLY=1
       - MUST_LOGIN=N
       - TZ=Asia/Shanghai
       - RUSTDESK_API_KEY_FILE=/data/id_ed25519.pub
       - RUSTDESK_API_JWT_KEY=ujqgLD8BOkcCUtly # jwt key
     volumes:
       - /data/rustdesk/server:/data
       - /data/rustdesk/api:/app/data #将数据库挂载
     networks:
       - rustdesk-net
     restart: unless-stopped
       
```

* 日志如下
```
{"log":"s6-rc: info: service s6rc-oneshot-runner: starting\n","stream":"stderr","time":"2025-02-16T02:01:58.309922538Z"}
{"log":"s6-rc: info: service s6rc-oneshot-runner successfully started\n","stream":"stderr","time":"2025-02-16T02:01:58.314788547Z"}
{"log":"s6-rc: info: service fix-attrs: starting\n","stream":"stderr","time":"2025-02-16T02:01:58.315308571Z"}
{"log":"s6-rc: info: service key-secret: starting\n","stream":"stderr","time":"2025-02-16T02:01:58.316018109Z"}
{"log":"s6-rc: info: service key-secret successfully started\n","stream":"stderr","time":"2025-02-16T02:01:58.322555651Z"}
{"log":"s6-rc: info: service hbbr: starting\n","stream":"stderr","time":"2025-02-16T02:01:58.3232318Z"}
{"log":"s6-rc: info: service fix-attrs successfully started\n","stream":"stderr","time":"2025-02-16T02:01:58.324579704Z"}
{"log":"s6-rc: info: service legacy-cont-init: starting\n","stream":"stderr","time":"2025-02-16T02:01:58.325201401Z"}
{"log":"s6-rc: info: service hbbr successfully started\n","stream":"stderr","time":"2025-02-16T02:01:58.327922935Z"}
{"log":"s6-rc: info: service hbbs: starting\n","stream":"stderr","time":"2025-02-16T02:01:58.334079835Z"}
{"log":"s6-rc: info: service hbbs successfully started\n","stream":"stderr","time":"2025-02-16T02:01:58.340073724Z"}
{"log":"s6-rc: info: service api: starting\n","stream":"stderr","time":"2025-02-16T02:01:58.340855102Z"}
{"log":"s6-rc: info: service legacy-cont-init successfully started\n","stream":"stderr","time":"2025-02-16T02:01:58.341500603Z"}
{"log":"s6-rc: info: service api successfully started\n","stream":"stderr","time":"2025-02-16T02:01:58.345286616Z"}
{"log":"s6-rc: info: service legacy-services: starting\n","stream":"stderr","time":"2025-02-16T02:01:58.346173532Z"}
{"log":"s6-rc: info: service legacy-services successfully started\n","stream":"stderr","time":"2025-02-16T02:01:58.354194246Z"}
{"log":"[2025-02-16 10:01:58.640417 +08:00] INFO [src/common.rs:147] Private/public key written to id_ed25519/id_ed25519.pub\n","stream":"stdout","time":"2025-02-16T02:01:58.640829658Z"}
{"log":"[2025-02-16 10:01:58.640451 +08:00] INFO [src/relay_server.rs:582] Key: nJqr3uDyQulZBoeXq9+nWJdzubKZcMBhOshrjDsAca8=\n","stream":"stdout","time":"2025-02-16T02:01:58.641073957Z"}
{"log":"[2025-02-16 10:01:58.640474 +08:00] INFO [src/relay_server.rs:61] #blacklist(blacklist.txt): 0\n","stream":"stdout","time":"2025-02-16T02:01:58.641154311Z"}
{"log":"[2025-02-16 10:01:58.640484 +08:00] INFO [src/relay_server.rs:76] #blocklist(blocklist.txt): 0\n","stream":"stdout","time":"2025-02-16T02:01:58.641269376Z"}
{"log":"[2025-02-16 10:01:58.640487 +08:00] INFO [src/relay_server.rs:82] Listening on tcp :21117\n","stream":"stdout","time":"2025-02-16T02:01:58.641283156Z"}
{"log":"[2025-02-16 10:01:58.640490 +08:00] INFO [src/relay_server.rs:84] Listening on websocket :21119\n","stream":"stdout","time":"2025-02-16T02:01:58.641293017Z"}
{"log":"[2025-02-16 10:01:58.640493 +08:00] INFO [src/relay_server.rs:87] Start\n","stream":"stdout","time":"2025-02-16T02:01:58.641297496Z"}
{"log":"[2025-02-16 10:01:58.640768 +08:00] INFO [src/relay_server.rs:105] DOWNGRADE_THRESHOLD: 0.66\n","stream":"stdout","time":"2025-02-16T02:01:58.641301837Z"}
{"log":"[2025-02-16 10:01:58.640792 +08:00] INFO [src/relay_server.rs:115] DOWNGRADE_START_CHECK: 1800s\n","stream":"stdout","time":"2025-02-16T02:01:58.641312778Z"}
{"log":"[2025-02-16 10:01:58.640795 +08:00] INFO [src/relay_server.rs:125] LIMIT_SPEED: 4Mb/s\n","stream":"stdout","time":"2025-02-16T02:01:58.641316611Z"}
{"log":"[2025-02-16 10:01:58.640799 +08:00] INFO [src/relay_server.rs:136] TOTAL_BANDWIDTH: 1024Mb/s\n","stream":"stdout","time":"2025-02-16T02:01:58.641320628Z"}
{"log":"[2025-02-16 10:01:58.640801 +08:00] INFO [src/relay_server.rs:146] SINGLE_BANDWIDTH: 16Mb/s\n","stream":"stdout","time":"2025-02-16T02:01:58.641324535Z"}
{"log":"[2025-02-16 10:02:00.351655 +08:00] INFO [src/common.rs:121] Private key comes from id_ed25519\n","stream":"stdout","time":"2025-02-16T02:02:00.351898153Z"}
{"log":"[2025-02-16 10:02:00.351704 +08:00] INFO [src/rendezvous_server.rs:1349] Key: nJqr3uDyQulZBoeXq9+nWJdzubKZcMBhOshrjDsAca8=\n","stream":"stdout","time":"2025-02-16T02:02:00.351969081Z"}
{"log":"[2025-02-16 10:02:00.351711 +08:00] INFO [src/peer.rs:84] DB_URL=./db_v2.sqlite3\n","stream":"stdout","time":"2025-02-16T02:02:00.352014734Z"}
{"log":"[2025-02-16 10:02:00.354469 +08:00] INFO [libs/hbb_common/src/config.rs:902] Generated new keypair for id: \n","stream":"stdout","time":"2025-02-16T02:02:00.354732566Z"}
{"log":"[2025-02-16 10:02:00.375007 +08:00] INFO [src/rendezvous_server.rs:114] serial=0\n","stream":"stdout","time":"2025-02-16T02:02:00.375309673Z"}
{"log":"[2025-02-16 10:02:00.375054 +08:00] INFO [src/common.rs:45] rendezvous-servers=[]\n","stream":"stdout","time":"2025-02-16T02:02:00.375355344Z"}
{"log":"[2025-02-16 10:02:00.375058 +08:00] INFO [src/rendezvous_server.rs:116] Listening on tcp/udp :21116\n","stream":"stdout","time":"2025-02-16T02:02:00.375361277Z"}
{"log":"[2025-02-16 10:02:00.375062 +08:00] INFO [src/rendezvous_server.rs:117] Listening on tcp :21115, extra port for NAT test\n","stream":"stdout","time":"2025-02-16T02:02:00.375365624Z"}
{"log":"[2025-02-16 10:02:00.375064 +08:00] INFO [src/rendezvous_server.rs:118] Listening on websocket :21118\n","stream":"stdout","time":"2025-02-16T02:02:00.37537037Z"}
{"log":"[2025-02-16 10:02:00.375661 +08:00] INFO [src/rendezvous_server.rs:157] mask: None\n","stream":"stdout","time":"2025-02-16T02:02:00.37583669Z"}
{"log":"[2025-02-16 10:02:00.375676 +08:00] INFO [src/rendezvous_server.rs:158] local-ip: \"\"\n","stream":"stdout","time":"2025-02-16T02:02:00.375890988Z"}
{"log":"[2025-02-16 10:02:00.535113 +08:00] INFO [src/common.rs:45] relay-servers=[]\n","stream":"stdout","time":"2025-02-16T02:02:00.535267546Z"}
{"log":"[2025-02-16 10:02:00.535434 +08:00] INFO [src/rendezvous_server.rs:172] ALWAYS_USE_RELAY=N\n","stream":"stdout","time":"2025-02-16T02:02:00.535547005Z"}
{"log":"[2025-02-16 10:02:00.535451 +08:00] INFO [src/rendezvous_server.rs:191] MUST_LOGIN=N\n","stream":"stdout","time":"2025-02-16T02:02:00.535671515Z"}
{"log":"[2025-02-16 10:02:00.535475 +08:00] INFO [src/rendezvous_server.rs:223] Start\n","stream":"stdout","time":"2025-02-16T02:02:00.535812962Z"}
{"log":"[2025-02-16 10:02:01] [INFO] migrating....260 (/home/runner/work/rustdesk-api/rustdesk-api/cmd/apimain.go:237 main.Migrate)\n","stream":"stdout","time":"2025-02-16T02:02:01.398653867Z"}
{"log":"[2025-02-16 10:02:01] [INFO] Admin Password Is: uZf5X9XV (/home/runner/work/rustdesk-api/rustdesk-api/cmd/apimain.go:294 main.Migrate)\n","stream":"stdout","time":"2025-02-16T02:02:01.596075622Z"}
{"log":"[2025-02-16 10:02:01] [INFO] API SERVER START (/home/runner/work/rustdesk-api/rustdesk-api/cmd/apimain.go:42 main.init.func2)\n","stream":"stdout","time":"2025-02-16T02:02:01.601699103Z"}
{"log":"2025/02/16 10:02:01 105 0.0.0.0:21114\n","stream":"stderr","time":"2025-02-16T02:02:01.602767481Z"}
{"log":"[2025-02-16 10:02:01.995150 +08:00] INFO [src/peer.rs:102] update_pk 172119171 [::ffff:117.147.32.107]:1565 b\"0e4d7f61-9393-4dc3-95f1-ee0d67343c0d\" b\"jiB\u003c\\xe2f1\\xe4f\\x16\\xc1\\xc7TY\\x1a@Xh\\x1b\\xc3\\x11'\\xca\\xd6\\xea\\xf7\\x89n\\x8fZ\\xebx\"\n","stream":"stdout","time":"2025-02-16T02:02:01.995510815Z"}
{"log":"[2025-02-16 10:02:03.043003 +08:00] INFO [src/peer.rs:102] update_pk 1649174796 [::ffff:43.248.79.99]:50886 b\"f0d29229-5e92-41a6-b2da-bfc1db5943be\" b\"\\xd7P\\xde\\x97\\n#\\x8e\\xeb\\xabb\\x88h$\\x7f\\x90I\\xda\\xfe=.\\x8f\\x88f\\xa4\\xe7C\\n[\\x15\u003e\\x9d\\x0e\"\n","stream":"stdout","time":"2025-02-16T02:02:03.043340915Z"}
{"log":"[2025-02-16 10:02:04.488755 +08:00] INFO [src/peer.rs:102] update_pk 78772324 [::ffff:221.236.27.73]:65364 b\"3e7692e2-4894-45c4-a300-a6c88c324c5a\" b\"\\xc1gH\\xc7\\x89\\xd4Y\\xe1\\xc2Ww\\x9f\\x8eN\\x83'@\\xc3Pv\\xf1\\xaf?\\xce\\x13\\x1e\\xbd\\x9e\\xa6\\r\\x13\\xde\"\n","stream":"stdout","time":"2025-02-16T02:02:04.489128453Z"}
{"log":"[2025-02-16 10:02:06.286554 +08:00] INFO [src/peer.rs:102] update_pk 286991702 [::ffff:117.147.32.107]:1539 b\"e27da8df-a693-4421-b364-a34a825ec43c\" b\"\\x1f\\t\\xbf\\xe2\\x96\\xcaX  }\\xfc\\x10\\x90_\\xd3n8\\xa7\\x91\\xab\\xb9\\n\\0\\xde\\xddD\\xc1E\\xc6\\xa3\\xa1\\x9d\"\n","stream":"stdout","time":"2025-02-16T02:02:06.286877355Z"}
{"log":"[2025-02-16 10:02:18.512800 +08:00] INFO [src/relay_server.rs:452] New relay request 605b2e84-f0bb-4f50-b323-b5a38aee13c7 from [::ffff:117.147.32.107]:1601\n","stream":"stdout","time":"2025-02-16T02:02:18.513016134Z"}
{"log":"[2025-02-16 10:02:36.655609 +08:00] INFO [src/relay_server.rs:452] New relay request 64a28208-9bdc-40b1-a39c-028f4abb9fc2 from [::ffff:117.147.32.107]:1687\n","stream":"stdout","time":"2025-02-16T02:02:36.655775778Z"}
{"log":"[2025-02-16 10:02:55.998118 +08:00] INFO [src/relay_server.rs:452] New relay request 27f161e6-348d-49c5-8fc8-048b39ea0a6c from [::ffff:117.147.32.107]:1556\n","stream":"stdout","time":"2025-02-16T02:02:55.998351549Z"}
{"log":"[2025-02-16 10:03:16.312858 +08:00] INFO [src/relay_server.rs:452] New relay request 8772a0d6-8efb-4155-9555-dab82cc45d29 from [::ffff:117.147.32.107]:1631\n","stream":"stdout","time":"2025-02-16T02:03:16.313130194Z"}
{"log":"[2025-02-16 10:03:38.703681 +08:00] INFO [src/relay_server.rs:452] New relay request f1978510-f237-40e9-8115-9d02db11af56 from [::ffff:117.147.32.107]:1757\n","stream":"stdout","time":"2025-02-16T02:03:38.703916782Z"}
{"log":"[2025-02-16 10:03:45.235398 +08:00] INFO [src/relay_server.rs:452] New relay request ae456423-0e1e-4bea-8d04-83f14a8b4222 from [::ffff:117.147.32.107]:1568\n","stream":"stdout","time":"2025-02-16T02:03:45.235615977Z"}
{"log":"[2025-02-16 10:04:04.646276 +08:00] INFO [src/relay_server.rs:452] New relay request 38530b47-432b-4500-96bc-36faa61124a4 from [::ffff:117.147.32.107]:1655\n","stream":"stdout","time":"2025-02-16T02:04:04.64653384Z"}
{"log":"[2025-02-16 10:04:25.063707 +08:00] INFO [src/relay_server.rs:452] New relay request 95fb522a-40eb-4b79-923b-90dc208758a1 from [::ffff:117.147.32.107]:1728\n","stream":"stdout","time":"2025-02-16T02:04:25.063887003Z"}
{"log":"[2025-02-16 10:04:47.446022 +08:00] INFO [src/relay_server.rs:452] New relay request 93337942-30f5-4a06-a3c8-e61be51a3f69 from [::ffff:117.147.32.107]:1594\n","stream":"stdout","time":"2025-02-16T02:04:47.44622611Z"}
{"log":"[2025-02-16 10:04:50.283437 +08:00] INFO [src/relay_server.rs:452] New relay request becbb63a-b12d-4ab1-9706-eb5c7e366408 from [::ffff:117.147.32.107]:1625\n","stream":"stdout","time":"2025-02-16T02:04:50.283605348Z"}
{"log":"[2025-02-16 10:05:01.368420 +08:00] INFO [src/relay_server.rs:452] New relay request a08a7a30-96eb-446e-ba60-dc04c02eff3f from [::ffff:117.147.32.107]:1680\n","stream":"stdout","time":"2025-02-16T02:05:01.368614666Z"}

```
